/*This question is very mathematical you first draw the grid for the n values
for example if for n=3
0->a->2a
0->a->(a+b)
0->b->(a+b)
0->b->(2b)


a+b is generated by (2a + (b-a)) and so on
till (2b) i.e (n-1 * a) -> (n-1*b) with the diff (b - a) added to each of the things

*/
#include <iostream>
#include <math.h>

using namespace std;

int main( ){

  int t;
  int n,a,b;

  cin>>t;
  for(int i = 0;i < t;i++){

               cin>>n>>a>>b;

               int diff = abs(a-b);

               for(int j = (a*(n-1));j <= ((n-1)*b);j += diff){
                                    cout<<(j)<<" ";
               }
               cout<<endl;
  }
 return 0;
}
